### ISSUE TITLE
Executing `sudo -n $COMMAND` inside Toolbx fails

### ISSUE THREAD

**Issue by exponentactivity** [containers/toolbox#1058]
**Describe the bug**
Executing `sudo` with the `--non-interactive` option fails inside Toolbx
```sh
$ sudo -n whoami
sudo: a password is required
```

**Steps how to reproduce the behaviour**
1. Create a new toolbox: `toolbox create --distro fedora test`
2. Enter toolbox `toolbo enter test`
3. Execute `sudo -n whoami`

**Expected behaviour**
Command executes and returns `root`.

**Actual behaviour**
Returns `sudo: a password is required`

**Workaround**
1. Execute sudo without the `-n` option before step 3.

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.3`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.3-2.fc35.x86_64`

**Output of `podman version`**
```
Version:      3.4.7
API Version:  3.4.7
Go Version:   go1.16.15
Built:        Thu Apr 21 15:14:26 2022
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
` podman-3:3.4.7-1.fc35.x86_64`

**Info about your OS**
Fedora Silverblue 35

**Additional context**
I discovered this bug while running an Ansible task as root inside the toolbox container.

Example playbook:
```yaml
- hosts: localhost
  tasks:
    - name: Run a module as sudo
      ansible.builtin.command: whoami
      become: true
      become_method: sudo
```
