### ISSUE TITLE
Consider using a config file

### ISSUE THREAD

**Issue by njam** [containers/toolbox#476]
Have you considered using a config file to define the toolbox containers? I can find an old PR on the topic (https://github.com/containers/toolbox/pull/100), but no ticket.

Using a config file has mainly two advantages imo:
- Allows for more fine-grained configuration of aspects of the container _creation_ but also of container _runtime_. (For example what shell to use in the container.)
- Separate command `create` and `enter` not needed anymore. Containers could be created on-demand in `enter`, based on the configuration file.

For example something like this:
```toml
[toolbox.fedora]
image = "registry.fedoraproject.org/f32/fedora-toolbox:32"
workdir = "~/Projects"
shell = "bash"

[toolbox.debian]
image = "docker.io/library/debian:10"
workdir = "~/Projects"
shell = "zsh"
```

Here's a demo of how this could work: https://gitlab.com/njam/toolbox-njam#configure-toolbox-containers
